spring.application.name=rider

server.port=9020

spring.datasource.url = jdbc:mysql://localhost:3306/riderdb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username = root
spring.datasource.password = Janhvee@12


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092