spring.application.name=servicediscovery
eureka.client.registerWithEureka = false
eureka.client.fetchRegistry = false
server.port = 8761



#Normally, Eureka clients (like orderms, paymentms) register themselves with Eureka Server.

#But here, this app is the Eureka Server itself.
#So, no need for the server to register itself. Thats why = false.



#Eureka clients usually fetch registry (the list of all services) from Eureka Server.
#
#But the server doesnt need to fetch its own registry.
#So, false